development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "gogoroproject@gmail.com"
  password: "GoGaming123456"
  enable_starttls_auto: true

production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["EMAIL_USERNAME"] %>
  password:  <%= ENV["EMAIL_PASSWORD"] %>
  enable_starttls_auto: true